import { Inter } from "next/font/google";
import "./globals.css";
import { Caudex } from 'next/font/google';
import { Taviraj } from 'next/font/google';


const caudex = Caudex({
  weight: '400',
  subsets: ['latin'],
})

const taviraj = Taviraj({
  subsets: ['latin'],
  weight: '400'
})
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Vlog - the latest insights",
  description: "AI Vlog - the latest insights: Is a blog website for AI enthusiasts. all the content are generated by AI.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${caudex.className} ${taviraj.className}  min-h-screen relative flex flex-col`}>{children}</body>
    </html>
  );
}
