/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dUSB5qzxtz4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Taviraj } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"

export function Home() {
  return (<>
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                Discover the Latest Insights
              </h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Explore our collection of thought-provoking articles and stay ahead of the curve.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#">
                Read the Blog
              </Link>
            </div>
          </div>
          <img
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
            height="550"
            src="/placeholder.svg"
            width="550" />
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Posts</h2>
            <p
              className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Check out our latest and greatest blog posts.
            </p>
          </div>
        </div>
        <div
          className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3">
          <Card>
            <img
              alt="Blog Post"
              className="aspect-video overflow-hidden rounded-t-xl object-cover"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="space-y-2 p-4">
              <h3 className="text-xl font-bold">Unlocking the Power of Serverless: A Beginner's Guide</h3>
              <p className="text-gray-500 line-clamp-3 dark:text-gray-400">
                Discover how serverless architecture can revolutionize your development workflow and unlock new levels
                of scalability and cost-efficiency.
              </p>
              <Link
                className="inline-flex items-center gap-1 text-sm font-medium text-gray-900 hover:underline dark:text-gray-50"
                href="#">
                Read More
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Blog Post"
              className="aspect-video overflow-hidden rounded-t-xl object-cover"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="space-y-2 p-4">
              <h3 className="text-xl font-bold">Mastering React Hooks: A Comprehensive Guide</h3>
              <p className="text-gray-500 line-clamp-3 dark:text-gray-400">
                Dive deep into the world of React Hooks and learn how to leverage these powerful tools to build more
                efficient and maintainable applications.
              </p>
              <Link
                className="inline-flex items-center gap-1 text-sm font-medium text-gray-900 hover:underline dark:text-gray-50"
                href="#">
                Read More
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Blog Post"
              className="aspect-video overflow-hidden rounded-t-xl object-cover"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <CardContent className="space-y-2 p-4">
              <h3 className="text-xl font-bold">Optimizing Web Performance: Strategies and Best Practices</h3>
              <p className="text-gray-500 line-clamp-3 dark:text-gray-400">
                Learn proven techniques to improve the speed and responsiveness of your web applications, ensuring a
                seamless user experience.
              </p>
              <Link
                className="inline-flex items-center gap-1 text-sm font-medium text-gray-900 hover:underline dark:text-gray-50"
                href="#">
                Read More
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore by Category</h2>
            <p
              className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Browse our collection of blog posts by category.
            </p>
          </div>
          <div
            className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
            <Link
              className="rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-900 transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
              href="#">
              JavaScript
            </Link>
            <Link
              className="rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-900 transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
              href="#">
              React
            </Link>
            <Link
              className="rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-900 transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
              href="#">
              CSS
            </Link>
            <Link
              className="rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-900 transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
              href="#">
              Performance
            </Link>
            <Link
              className="rounded-md bg-gray-100 px-4 py-2 text-sm font-medium text-gray-900 transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
              href="#">
              Serverless
            </Link>
          </div>
        </div>
      </div>
    </section>
  </>);
}

function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}
